version: "3.9"

services:
  worker:
    build: .
    command: python3.9 src/same_story_api/app.py
    volumes:
      # yaml anchor
      &volumes
      - ${HOME}/.npm:${HOME}/.npm
      - .:/code
      - /run/same-story-api:/run/same-story-api
    env_file: .env
  celery:
    build: .
    command: celery -A same_story_api.tasks worker --loglevel=INFO
    volumes: *volumes
    env_file: .env
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
    volumes: *volumes
    env_file: .env
    depends_on:
      - "worker"
