version: "3.9"

services:
  worker:
    build: .
    command: python3.9 src/same_story_api/app.py
    volumes:
      - .:/code
      - ${HOME}/.npm:${HOME}/.npm
    env_file: .env
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - "worker"
