version: "3.9"

services:
  worker:
    build: .
    command: python3.9 src/same_story_api/app.py
    volumes:
      # yaml anchor
      &volumes
      - ${HOME}/.npm:${HOME}/.npm
      - .:/code
      - /run/same-story-api:/run/same-story-api
    env_file: .env
  celery:
    build: .
    command: celery -A engi_message_queue.tasks worker --loglevel=INFO -B
    volumes: *volumes
    env_file: .env
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest -v -s # test/test_same_story_server.py::test_should_error_on_repo_problem
    volumes: *volumes
    env_file: .env
    depends_on:
      - "worker"
