version: "3.9"

services:
  worker:
    build: .
    environment:
      - QUEUE_URL=$QUEUE_URL
    command: python3.9 src/same_story_api/app.py
    volumes:
      - .:/code
      - ${HOME}/.npm:${HOME}/.npm
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - TOPIC_ARN=$TOPIC_ARN
    command: pytest
    volumes:
      - .:/code
    depends_on:
      - "worker"
